### ISSUE TITLE
Bugs with aggregates

### ISSUE THREAD

**Issue by bourtemb** [tango-controls-hdbpp/hdbpp-viewer#7]
It seems like the user has the possibility to try to display aggregates of the set points for ReadOnly attributes which do not have set points (MEAN_W aggregate value for instance). This is a bit strange and when used, nothing appears on the plots any more nor on the table if table checkbox is ticked, even for the attributes for which we had some values displayed before.

Normal view before the user tries to display MIN_W value:
![Screenshot_HDBViewerOK](https://user-images.githubusercontent.com/16306867/106466300-73c60d80-649b-11eb-82af-1acc4c7007da.png)

Problem after trying to display MIN_W value too:
![Screenshot_HDBViewerNotOK](https://user-images.githubusercontent.com/16306867/106466327-79235800-649b-11eb-9fea-b226315a55b6.png)

No error is reported by the user interface (even in the View -> Errors... menu) but nothing is displayed in the chart tab nor in table tab.

There is also another problem when removing an aggregate from the selection.
One can select 1 aggregate in the attributes selection at the bottom of the window and then click on Remove button but this seems to remove all the aggregates from the selection whereas one would expect that only the aggregate which was selected before clicking on Remove button would be removed.

**Comment by JeanLucPons** [comment]
Both problems fixed In 1.26
Note the _W aggregates are related to setpoint and are not filled for read only value. Now, on such a selection you will have 0 records indicated in the _W aggrates and empty associated curve.
